version: "3.7"
services:
  app:
      build:
        args:
          user: luis
          uid: 1000
        context: ./
        dockerfile: app.dockerfile
      image: safmtv
      container_name: safmtv-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - safmtv

  postgres:
    image: postgres:13.2
    container_name: safmtv-db
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
      - ./docker-compose/pgsql:/docker-entrypoint-initdb.d
    networks:
      - safmtv

  nginx:
    image: nginx:stable
    container_name: safmtv-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      safmtv:
        aliases:
            - saf-mtv.test


networks:
  safmtv:
    driver: bridge
