<?php

namespace App\Models;

class ProductoColor 
{
    // Lista de códigos de colores con etiqueta seleccionables, depurada por el equipo MTV.
    // La lista vigente de colores en español corresponde a la lista de la plantilla de carga masiva de productos.
    // Ver plantilla en: /storage/app/public/plantillas/productos_carga_masiva.xlsx
    public const PRODUCTO_CSS_COLOR_NAMES = [
        // "AliceBlue",
        // "AntiqueWhite",
        'Aqua' => 'Azul turqueza',
        // "Aquamarine",
        // "Azure",
        // "Beige",
        // "Bisque",
        'Black' => 'Negro',
        // "BlanchedAlmond",
        'Blue' => 'Azul',
        // "BlueViolet",
        // "Brown",
        // "BurlyWood",
        // "CadetBlue",
        // "Chartreuse",
        // "Chocolate",
        // "Coral",
        // "CornflowerBlue",
        'Cornsilk' => 'Crema',
        // "Crimson",
        // "Cyan",
        // "DarkBlue",
        // "DarkCyan",
        'DarkGoldenRod' => 'Verde militar',
        // "DarkGray",
        // "DarkGrey",
        // "DarkGreen",
        // "DarkKhaki",
        // "DarkMagenta",
        // "DarkOliveGreen",
        // "DarkOrange",
        // "DarkOrchid",
        'DarkRed' => 'Vino',
        // "DarkSalmon",
        // "DarkSeaGreen",
        // "DarkSlateBlue",
        // "DarkSlateGray",
        // "DarkSlateGrey",
        // "DarkTurquoise",
        // "DarkViolet",
        'DeepPink' => 'Rosa mexicano',
        // "DeepSkyBlue",
        // "DimGray",
        // "DimGrey",
        // "DodgerBlue",
        // "FireBrick",
        // "FloralWhite",
        // "ForestGreen",
        // "Fuchsia",
        // "Gainsboro",
        // "GhostWhite",
        'Gold' => 'Dorado',
        // "GoldenRod",
        'Gray' => 'Gris',
        // "Grey",
        'Green' => 'Verde',
        'GreenYellow' => 'Verde limón',
        // "HoneyDew",
        // "HotPink",
        // "IndianRed",
        // "Indigo",
        // "Ivory",
        // "Khaki",
        // "Lavender",
        // "LavenderBlush",
        // "LawnGreen",
        // "LemonChiffon",
        // "LightBlue",
        // "LightCoral",
        // "LightCyan",
        // "LightGoldenRodYellow",
        // "LightGray",
        // "LightGrey",
        // "LightGreen",
        // "LightPink",
        // "LightSalmon",
        // "LightSeaGreen",
        // "LightSkyBlue",
        // "LightSlateGray",
        // "LightSlateGrey",
        // "LightSteelBlue",
        // "LightYellow",
        // "Lime",
        // "LimeGreen",
        // "Linen",
        // "Magenta",
        'Maroon' => 'Shedron',
        // "MediumAquaMarine",
        // "MediumBlue",
        // "MediumOrchid",
        // "MediumPurple",
        // "MediumSeaGreen",
        // "MediumSlateBlue",
        // "MediumSpringGreen",
        // "MediumTurquoise",
        // "MediumVioletRed",
        'MidnightBlue' => 'Azul marino',
        // "MintCream",
        // "MistyRose",
        // "Moccasin",
        // "NavajoWhite",
        // "Navy",
        // "OldLace",
        'Olive' => 'Verde claro',
        // "OliveDrab",
        'Orange' => 'Naranja',
        'OrangeRed' => 'Naranja vivido',
        // "Orchid",
        // "PaleGoldenRod",
        // "PaleGreen",
        // "PaleTurquoise",
        // "PaleVioletRed",
        // "PapayaWhip",
        // "PeachPuff",
        // "Peru",
        'Pink' => 'Rosa',
        // "Plum",
        // "PowderBlue",
        'Purple' => 'Morado',
        // "RebeccaPurple",
        'Red' => 'Rojo',
        // "RosyBrown",
        // "RoyalBlue",
        // "SaddleBrown",
        // "Salmon",
        // "SandyBrown",
        // "SeaGreen",
        // "SeaShell",
        'Sienna' => 'Café',
        'Silver' => 'Gris claro',
        'SkyBlue' => 'Azul cielo',
        // "SlateBlue",
        // "SlateGray",
        // "SlateGrey",
        // "Snow",
        // "SpringGreen",
        // "SteelBlue",
        // "Tan",
        // "Teal",
        'Thistle' => 'Lila',
        // "Tomato",
        // "Turquoise",
        // "Violet",
        // "Wheat",
        'White' => 'Blanco',
        // "WhiteSmoke",
        'Yellow' => 'Amarillo',
        // "YellowGreen",
    ];

    /**
     * Recibe una cadena con colores en idioma español y los traduce a códigos de color.
     */
    public static function traduceColoresCodigos(string $colores): string
    {        
        if (!empty($colores)) {
            $coloresCodigos = explode(',', $colores);
            array_walk($coloresCodigos, function(&$item) {
                $item = trim($item);
                $item = array_search($item, self::PRODUCTO_CSS_COLOR_NAMES);
            });

            // Remover elementos no encontrados (vacíos)
            array_filter($coloresCodigos);
            
            return implode(',', $coloresCodigos);
        }

        return '';
    }
}